Repository Adyen/adyen-apex-api-library, pull requests merged in 2024-05, with the labels that each got.

#44 Applying PR template
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: ignore-for-release

#42 SepaDirectDebitDetails and PaymentsResponse classes update
  force-app/main/default/classes/PaymentsResponse.cls
  force-app/main/default/classes/SepaDirectDebitDetails.cls
Labels: enhancement

#47 Updating model for ACH payment method
  .github/workflows/unit-tests.yml
  force-app/main/default/classes/ACHDetails.cls
  force-app/main/default/classes/ACHDetails.cls-meta.xml
  force-app/main/default/classes/ACHDetailsTest.cls
  force-app/main/default/classes/ACHDetailsTest.cls-meta.xml
Labels: enhancement

#49 Enable alternative payments: updating SEPA and ACH models
  force-app/main/default/classes/ACHDetails.cls
  force-app/main/default/classes/ACHDetails.cls-meta.xml
  force-app/main/default/classes/ACHDetailsTest.cls
  force-app/main/default/classes/ACHDetailsTest.cls-meta.xml
  force-app/main/default/classes/PaymentsResponse.cls
  force-app/main/default/classes/SepaDirectDebitDetails.cls
Labels: new
